name: loc_logger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  background_fetch: ^1.3.4
  flutter:
    sdk: flutter
  geodesy: ^0.10.2
  geolocator: ^11.0.0
  geolocator_android: ^4.6.0
  geolocator_apple: ^2.3.7
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  uuid: ^4.4.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
